Fulgurio\LightCMSBundle\Entity\Media:
  type: entity
  repositoryClass: Fulgurio\LightCMSBundle\Repository\MediaRepository
  table: media
  indexes:
      owner_idx:
          columns: [owner_id]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    original_name:
      type: string
      length: 64
    full_path:
      type: string
      length: 255
      nullable: true
    media_type:
      type: string
      length: 16
    owner_id:
      type: integer
      nullable: true
    created_at:
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: update
