Fulgurio\LightCMSBundle\Entity\PageMenu:
  type: entity
  repositoryClass: Fulgurio\LightCMSBundle\Repository\PageMenuRepository
  table: page_menu
  indexes:
    label_idx:
      columns: label
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    label:
      index:
      type: string
      length: 255
    position:
      type: integer
  manyToOne:
    page:
      targetEntity: Page
      inversedBy: menu
      joinColumn:
        onDelete: CASCADE
