Fulgurio\LightCMSBundle\Entity\Page:
  type: entity
  repositoryClass: Fulgurio\LightCMSBundle\Repository\PageRepository
  table: page
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    page_type:
      type: string
      length: 8
    title:
      type: string
      length: 255
    fullpath:
      type: string
      length: 255
      nullable: true
    slug:
      type: string
      length: 255
      nullable: true
    position:
      type: integer
    status:
      type: string
      length: 10
    content:
      type: text
      nullable: true
    model:
      type: string
      length: 255
      nullable: true
    created_at:
      type: datetime
      gedmo:
        timestampable:
          on: create
      nullable: true
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
      nullable: true
  oneToMany:
    children:
      targetEntity: Page
      mappedBy: parent
      cascade: [ remove ]
      orderBy:
        position: ASC
    meta:
      targetEntity: PageMeta
      mappedBy: page
      cascade: [ remove ]
  manyToOne:
    parent:
      targetEntity: Page
      inversedBy: children
