LightCMS_Admin_Users:
    resource: "@FulgurioLightCMSBundle/Resources/config/routing/admin_user.yml"
    prefix:   /admin/users

LightCMS_Admin_Menus:
    resource: "@FulgurioLightCMSBundle/Resources/config/routing/admin_menu.yml"
    prefix:   /admin/menus

LightCMS_Admin_Medias:
    resource: "@FulgurioLightCMSBundle/Resources/config/routing/admin_media.yml"
    prefix:   /admin/medias

LightCMS_Admin_Pages:
    resource: "@FulgurioLightCMSBundle/Resources/config/routing/admin_page.yml"
    prefix:   /admin/pages

LightCMS_Admin_Homepage:
    pattern:   /admin/
    defaults:  { _controller: FulgurioLightCMSBundle:AdminDashboard:index }

LightCMS_login:
    pattern:   /login
    defaults:  { _controller: FulgurioLightCMSBundle:Security:login }

LightCMS_login_check:
    pattern:  /login_check

LightCMS_logout:
    pattern:  /logout

LightCMS_Page:
    pattern:  /{fullpath}
    defaults: { _controller: FulgurioLightCMSBundle:FrontPage:show }
    requirements:
        fullpath: ".*"
