services:
    fulgurio_light_cms.action_listener:
        class: Fulgurio\LightCMSBundle\EventListener\BeforeListener
        arguments:
            doctrine: "@doctrine"
            kernel: "@kernel"
            securityContext: "@security.context"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    fulgurio_light_cms.twig.extension:
        class: Fulgurio\LightCMSBundle\Extension\LightCMSTwigExtension
        tags:
            -  { name: twig.extension }
        arguments:
            router: "@router"
            doctrine: "@doctrine"
            container: "@service_container"
