Fulgurio\LightCMSBundle\Entity\Page:
    properties:
        title:
            - NotBlank: { message: fulgurio.lightcms.pages.add_form.title_is_required }
        model:
            - NotBlank: { message: fulgurio.lightcms.pages.add_form.model_is_required }
        status:
            - Choice: { choices: [draft, published], message: fulgurio.lightcms.pages.add_form.status_is_required }

Fulgurio\LightCMSBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: fulgurio.lightcms.users.add_form.username_is_already_used
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: fulgurio.lightcms.users.add_form.email_is_already_used
    properties:
        username:
            - NotBlank: { message: fulgurio.lightcms.users.add_form.username_is_required }
        email:
            - NotBlank: { message: fulgurio.lightcms.users.add_form.email_is_required }
            - Email: { message: fulgurio.lightcms.users.add_form.email_is_not_valid }
