<?php

namespace Fulgurio\LightCMSBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Knp\Component\Pager\Paginator;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
	public function findAllWithPagination($limit, $offset)
	{
		$query = $this->getEntityManager()->createQuery('SELECT m FROM FulgurioLightCMSBundle:Media m ORDER BY m.created_at DESC')->setMaxResults($limit)->setFirstResult($offset);
		return $query->getArrayResult();
	}

	public function count()
	{
		$query = $this->getEntityManager()->createQuery('SELECT COUNT(m) FROM FulgurioLightCMSBundle:Media m');
		return $query->getSingleScalarResult();
	}
}