<?php

namespace Fulgurio\LightCMSBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Knp\Component\Pager\Paginator;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    /**
     * Find all medias
     *
     * @param $paginator
     * @param integer $nbPostPerPage
     * @return ArrayCollection
     */
    public function findAllMedias(Paginator $paginator, $pageNb, $nbPostPerPage = 10)
    {
        $query = $this->getEntityManager()->createQuery('SELECT m FROM FulgurioLightCMSBundle:Media m ORDER BY m.created_at DESC');
        return $query->getResult();
//         return $paginator->paginate($query, $pageNb, $nbPostPerPage);
    }
}