<?php

namespace Fulgurio\LightCMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * Get next position in tree
     *
     * @param integer $parentId
     * @return integer
     */
    public function getNextPosition($parentId)
    {
        $query = $this->getEntityManager()->createQuery('SELECT MAX(p.position) FROM FulgurioLightCMSBundle:Page p WHERE p.parent=:parentId');
        $query->setParameter('parentId', $parentId);
        return ($query->getSingleScalarResult() + 1);
    }

}