AdminPostsAdd:
    pattern:  /add
    defaults: { _controller: FulgurioLightCMSBundle:AdminPost:add }

AdminPostsEdit:
    pattern:  /{pageId}/edit
    defaults: { _controller: FulgurioLightCMSBundle:AdminPost:edit }

AdminPostsRemove:
    pattern:  /{pageId}/remove
    defaults: { _controller: FulgurioLightCMSBundle:AdminPost:remove }

AdminPosts:
    pattern:  /
    defaults: { _controller: FulgurioLightCMSBundle:AdminPost:list }
